# Generated by Django 2.2.3 on 2019-10-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('F', 'Fiction'), ('N', 'Non-Fiction')], max_length=1),
        ),
    ]
