# Generated by Django 2.2.3 on 2019-11-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_orderitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='publisher_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='genre',
            field=models.CharField(choices=[('AA', 'Action and adventure'), ('AH', 'Alternate history'), ('AT', 'Anthology'), ('CH', 'Childrens'), ('CO', 'Comic book'), ('CR', 'Crime'), ('DR', 'Drama'), ('FT', 'Fairytale'), ('FA', 'Fantasy'), ('GN', 'Graphic novel'), ('HF', 'Historical fiction'), ('HO', 'Horror'), ('MY', 'Mystery'), ('PO', 'Poetry'), ('PT', 'Political thriller'), ('RO', 'Romance'), ('SF', 'Science fiction'), ('SS', 'Short story'), ('SP', 'Suspense'), ('TH', 'Thriller'), ('AR', 'Art'), ('AB', 'Autobiography'), ('BO', 'Biography'), ('BR', 'Book review'), ('CB', 'Cookbook'), ('DI', 'Diary'), ('EN', 'Encyclopedia'), ('GU', 'Guide'), ('HE', 'Health'), ('HI', 'History'), ('JO', 'Journal'), ('MA', 'Math'), ('ME', 'Memoir'), ('RS', 'Religion, spirituality, and new age'), ('TB', 'Textbook'), ('RE', 'Review'), ('SC', 'Science'), ('SH', 'Self help'), ('TR', 'Travel')], max_length=2),
        ),
    ]
