# Generated by Django 2.2.3 on 2019-11-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='book_title',
            field=models.CharField(default='The Great Gatsby', max_length=100),
            preserve_default=False,
        ),
    ]
