# Generated by Django 2.2.3 on 2019-11-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191111_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='author_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='author_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
