# Generated by Django 2.2.3 on 2019-11-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='user', max_length=100),
            preserve_default=False,
        ),
    ]
