# Generated by Django 2.2.3 on 2019-11-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191111_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='saved_for_later',
            field=models.BooleanField(default=False),
        ),
    ]
