# Generated by Django 2.2.3 on 2019-11-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='book_title',
            field=models.CharField(default='The Martian', max_length=100),
            preserve_default=False,
        ),
    ]
