# Generated by Django 2.2.3 on 2019-11-20 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_savedforlateritem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedforlateritem',
            name='user',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
