# Generated by Django 2.2.3 on 2019-11-28 03:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_item_bestseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
