# Generated by Django 2.2.3 on 2019-11-26 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191004_1519'),
        ('core', '0003_comment_book_title'),
        ('core', '0010_auto_20191120_1913'),
    ]

    operations = [
    ]
