# Generated by Django 2.2.3 on 2019-11-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_item_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
